src/Entity/Culture.php
<?php

namespace App\Entity;

use App\Repository\CultureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CultureRepository::class)]
class Culture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
   
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'donner le type au moins {{ limit }} caractères ',
        maxMessage: 'donner le type maximum {{ limit }} caractères',)]
    #[ORM\Column(length: 255)]
    private ?string $type = null;

   #[Assert\Date]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    
    private ?\DateTimeInterface $date_planting = null;
    
    #[Assert\Type(
        type: 'float',
        message: 'la quantité {{ value }} nest pas valide {{ type }}.',)]
   
    #[ORM\Column]
    private ?float $quantite = null;
   
    #[ORM\OneToMany(mappedBy: 'culture', targetEntity: Terrain::class)]
    private Collection $terrain;

    public function __construct()
    {

        $this->terrain = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDatePlanting(): ?\DateTimeInterface
    {
        return $this->date_planting;
    }

    public function setDatePlanting(\DateTimeInterface $date_planting): self
    {
        $this->date_planting = $date_planting;

        return $this;
    }

    public function getQuantite(): ?float
    {
        return $this->quantite;
    }

    public function setQuantite(float $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    /**
     * @return Collection<int, Terrain>
     */
    public function getTerrain(): Collection
    {
        return $this->terrain;
    }

    public function addTerrain(Terrain $terrain): self
    {
        if (!$this->terrain->contains($terrain)) {
            $this->terrain->add($terrain);
            $terrain->setCulture($this);
        }

        return $this;
    }

    public function removeTerrain(Terrain $terrain): self
    {
        if ($this->terrain->removeElement($terrain)) {
            // set the owning side to null (unless already changed)
            if ($terrain->getCulture() === $this) {
                $terrain->setCulture(null);
            }
        }

        return $this;
    }
}

src/Form/CultureType.php
<?php

namespace App\Form;

use App\Entity\Culture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class CultureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', TextType::class)
            ->add('date_planting',DateType::class)
            ->add('quantite',NumberType::class)
            ->add('ajouter',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Culture::class,
        ]);
    }
}

src/Controller/CultureController.php
<?php

namespace App\Controller;

use App\Entity\Culture;
use App\Form\CultureType;
use App\Repository\CultureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;


#[Route('/culture')]
class CultureController extends AbstractController
{
    #[Route('/', name: 'app_culture_index', methods: ['GET'])]
    public function index(CultureRepository $cultureRepository): Response
    {
        return $this->render('culture/index.html.twig', [
            'cultures' => $cultureRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_culture_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CultureRepository $cultureRepository): Response
    {
        $culture = new Culture();
        $form = $this->createForm(CultureType::class, $culture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $cultureRepository->save($culture, true);
            

            return $this->redirectToRoute('app_culture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('culture/new.html.twig', [
            'culture' => $culture,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_culture_show', methods: ['GET'])]
    public function show(Culture $culture): Response
    {
        return $this->render('culture/show.html.twig', [
            'culture' => $culture,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_culture_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Culture $culture, CultureRepository $cultureRepository): Response
    {
        $form = $this->createForm(CultureType::class, $culture);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $cultureRepository->save($culture, true);

            

            return $this->redirectToRoute('app_culture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('culture/edit.html.twig', [
            'culture' => $culture,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_culture_delete', methods: ['POST'])]
    public function delete(Request $request, Culture $culture, CultureRepository $cultureRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$culture->getId(), $request->request->get('_token'))) {
            $cultureRepository->remove($culture, true);
        }
        

        return $this->redirectToRoute('app_culture_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/culture/_delete_form.html.twig
<form method="post" action="{{ path('app_culture_delete', {'id': culture.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ culture.id) }}">
    <button class="btn">Delete</button>
</form>

templates/culture/_form.html.twig
{{ form_start(form) }}
    
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/culture/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Culture{% endblock %}

{% block body %}
  <h1>Edit Culture</h1>
<main style="
           display: flex;align-items: center;
            position: fixed;
            left: 200px;
            bottom: 200px;
            width: 90%;
            justify-content: center;
           
height: 400px;
            text-align: center;">
  
 <div class="row">
        <div  style="display: flex;align-items: center;justify-content: center;margin-top: 150px; padding: 10px;">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"> modifier </h5>

                    <!-- General Form Elements -->
                    {{ form_start(form) }}
                    <p>
                    <label for="inputText" class="col-sm-4 col-form-label">type</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.type,{'attr':{'class':'form-control'}}) }}
                    </div>
</p>
<p>
                    <label for="Text" class="col-sm-4 col-form-label">date_plantation</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.date_planting,{'attr':{'class':'form-control'}}) }}

                    </div>
                    </p>
                    <p>
                    <label for="inputText" class="col-sm-4 col-form-label">quantité</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.quantite,{'attr':{'class':'form-control'}}) }}
                    </div>
</p>
                    
                    {{ form_end(form) }}

                </div>
            </div>

        </div>

    </div>
    
{% endblock %}

templates/culture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Culture index{% endblock %}


{% block body %}
    <main style="
            position: fixed;
           
            left: 400px;
            bottom: 250px;
            width: 60%;
            height: 300px;
            text-align: center;">

 <div class="container">
    <h1>Culture index</h1>
    <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-primary" href="{{ path('app_culture_new') }} "> 
                    une nouvelle culture
                </a>
            </div>
            <div class="card-body">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>date_plantation</th>
                <th>Quantité</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for culture in cultures %}
            <tr>
                <td>{{ culture.id }}</td>
                <td>{{ culture.type }}</td>
                <td>{{ culture.datePlanting ? culture.datePlanting|date('Y-m-d') : '' }}</td>
                <td>{{ culture.quantite }}</td>
                <td>
                    <a class="btn btn-outline-info" href="{{ path('app_culture_show', {'id': culture.id}) }}">afficher</a>
                    <a class="btn btn-outline-success" href="{{ path('app_culture_edit', {'id': culture.id}) }}">modifier</a>
                      <a class="btn btn-outline-success" href="{{ path('app_culture_delete', {'id': culture.id}) }}">supprimer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
    
</div>

    
{% endblock %}

templates/culture/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}nouvelle Culture{% endblock %}
 
{% block body %}
<main style="
           display: flex;align-items: center;
            position: fixed;
            left: 200px;
            bottom: 150px;
            width: 90%;
            justify-content: center;
           textarea {
  font-family: inherit;
  font-size: 60%;
}
            flex-wrap: wrap;
            height: 300px;
            text-align: center;">
    <div class="row">
        

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Ajouter Culture </h5>

                    <!-- General Form Elements -->
                    
                   {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
                   <p>
                        <label for="inputText" class="col-sm-4 col-form-label">type</label>
                        <div class="col-sm-10">
                            {{ form_widget(form.type,{'attr':{'class':'form-control'}}) }}

                        </div>
                    {{ form_errors(form.type,{'attr':{'class':'text-danger'}}) }}

</p>
<p>
                    <label for="inputText" class="col-sm-4 col-form-label">date_plantation</label>
                        <div class="col-sm-10">
                            {{ form_widget(form.date_planting,{'attr':{'class':'form-control'}}) }}

                    </div>
                    {{ form_errors(form.date_planting,{'attr':{'class':'text-danger'}}) }}

                  </p> 
 <p>
                   {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
                        <label for="inputText" class="col-sm-4 col-form-label">quantité</label>
                        <div class="col-sm-10">
                            {{ form_widget(form.quantite,{'attr':{'class':'form-control'}}) }}

                        </div>
                    {{ form_errors(form.quantite,{'attr':{'class':'text-danger'}}) }}

</p>
                    {{ form_end(form) }}

               
            </div>

        </div>

    </div>


{% endblock %}

templates/culture/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Culture{% endblock %}

{% block body %}
<main style="
            position: fixed;
           
            left: 400px;
            bottom: 250px;
            width: 60%;
             height: 300px;
            text-align: center;">
           
    <h1>Culture</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ culture.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ culture.type }}</td>
            </tr>
            <tr>
                <th>date_plantation</th>
                <td>{{ culture.datePlanting ? culture.datePlanting|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Quantité</th>
                <td>{{ culture.quantite }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_culture_index') }}">back to list</a>

    <a href="{{ path('app_culture_edit', {'id': culture.id}) }}">edit</a>

    {{ include('culture/_delete_form.html.twig') }}
{% endblock %}